version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.1
  aws-cli: circleci/aws-cli@3.1.3
  aws-eks: circleci/aws-eks@2.2.0


jobs:
  deploy:
    docker: 
      - image: cimg/base:current
    steps:
      - checkout
      - aws-cli/install
      - kubernetes/install-kubectl
      - aws-cli/assume-role-with-web-identity:
          role-arn: "arn:aws:iam::483285841698:role/SolutionsEngineeringEKS"
          role-session-name: "cci-crossplane-demo-<< pipeline.number >>"
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: cera-apne1-japac
          aws-region: ap-northeast-1
      - kubernetes/create-or-update-resource:
          resource-file-path: ./crossplane/postgres-aws.yaml

workflows:
  main: 
    jobs:
      - deploy:
          context: empty-context #to trigger OIDC token generation